defaults:
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: overcooked-v1
ROLLOUT_LENGTH: 400 # rollout length must be greater than episode length
ENV_KWARGS:
  layout: counter_circuit
  do_reward_shaping: true
  random_reset: false
  random_obj_state: false 
  reward_shaping_params:
    PLACEMENT_IN_POT_REW: [2, -1] # reward for putting ingredients 
    PLATE_PICKUP_REWARD: [3, 3] # reward for picking up a plate
    SOUP_PICKUP_REWARD: [6, 6] # reward for picking up a ready soup
    ONION_PICKUP_REWARD: [-1, 2]
    COUNTER_PICKUP_REWARD: [0.1, -0.1]
    COUNTER_DROP_REWARD: [-0.1, 0.1]
    ONION_HOLDING: [-0.05, 0]
    PLATE_HOLDING: [0.02, 0]
    DISH_DISP_DISTANCE_REW: [0, 0]
    POT_DISTANCE_REW: [0, 0]
    SOUP_DISTANCE_REW: [0, 0]

TOTAL_TIMESTEPS: 3e6
SEED: 12345
LR: .001
NUM_ENVS: 8
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 16
NUM_CHECKPOINTS: 5
NUM_SEEDS: 3
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: False

# WandB Params
logger: 
  project: aht-benchmark
  entity: aht-project
  mode: offline # options: online, offline, disabled
  verbose: false
  log_train_out: true # whether to log the out dictionary

local_logger:
  save_figures: true
  save_train_out: true

hydra:
  job:
    name: ippo
    chdir: true
  run:
    dir: results/${ENV_NAME}/${ENV_KWARGS.layout}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
